name = "QuadraticSweep"
uuid = "aaa28fd6-eded-406a-ae04-21f319ad4e3a"
authors = ["marcharary "]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Combinatorics = "1.0.2"
DataFrames = "1.7.0"
Distributed = "1.11.0"
Ipopt = "1.6.6"
JuMP = "1.23.2"
LinearAlgebra = "1.11.0"
MathOptInterface = "1.31.2"
Plots = "1.40.8"
ProgressMeter = "1.10.2"
PyCall = "1.96.4"
Statistics = "1.11.1"
Suppressor = "0.2.8"
